name: 'Dependency Review'

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  check:
    uses: sovity/core-edc-github/.github/workflows/dependency-check.yml@0.7.2_2025-01-22_1
    secrets: inherit
