name: 'Dependency Review'

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  check:
    uses: sovity/core-edc-github/.github/workflows/dependency-check.yml@sovity-0.7.2.x-main
    secrets: inherit
