name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: the version to be released. If it ends with '.0' a proper release is created, bugfix otherwise
        required: true
        type: string

jobs:
  Prepare-Release:
    uses: sovity/core-edc-github/.github/workflows/prepare-release.yml@5ad1a49278025ebb93393ed891cbcebf2c481ecc #0.14.0_2025-08-21
    secrets: inherit
    with:
      version: ${{ inputs.version }}
