name: publish autodoc

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: version to be published
        required: false
        type: string

jobs:
  publish:
    uses: sovity/core-edc-github/.github/workflows/publish-autodoc.yml@255e962d85b9e0b972ced7cf9750e7333f172127 #pinned/0.17.0_2026-08-26 #main@2026-08-25
    secrets: inherit
    with:
      version: ${{ github.event.inputs.version }}
