name: publish openapi ui

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: sovity/core-edc-github/.github/workflows/publish-openapi-ui.yml@2a8d5ee91db61fa80792b75cd9f821179a17e683 #0.11.1_2025-03-10
    secrets: inherit
