name: publish autodoc

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: version to be published
        required: false
        type: string

jobs:
  publish:
    uses: sovity/core-edc-github/.github/workflows/publish-autodoc.yml@5ad1a49278025ebb93393ed891cbcebf2c481ecc #0.14.0_2025-08-21
    secrets: inherit
    with:
      version: ${{ github.event.inputs.version }}
