on:
  push:
    branches: [ "sovity/**" ]
  release:
    types: [ published ]
  pull_request:
    branches: [ "sovity/**" ]

jobs:
  build-gradle-project:
    name: Publish artefacts
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: "Debug Info"
        run: echo ${{ github.ref }} ; echo ${GITHUB_REF}

      - name: "Gradle: Check"
        run: ./gradlew check

      - name: "Gradle: Publish to Production"
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: |
          GRADLE_ARGS="-Pversion=${GITHUB_REF#refs/tags/v}"
          ./gradlew --parallel "$GRADLE_ARGS" publishAllPublicationsToAzureRepository
        env:
          # AZURE_TOKEN with Packaging (Read, write, & manage); Release (Read, write, execute, & manage)
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}

      - name: "Gradle: Publish to Test"
        if: ${{ startsWith(github.ref, 'refs/heads/sovity/') }}
        run: |
          GRADLE_ARGS="-Pversion=${GITHUB_REF#refs/heads/sovity/}.0.$(date '+%Y%m%d.%H%M%S')"
          ./gradlew --parallel "$GRADLE_ARGS" publishAllPublicationsToAzureTestRepository
        env:
          # AZURE_TOKEN with Packaging (Read, write, & manage); Release (Read, write, execute, & manage)
          AZURE_TOKEN: ${{ secrets.AZURE_TOKEN }}
