name: publish openapi ui

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: sovity/core-edc-github/.github/workflows/publish-openapi-ui.yml@5ad1a49278025ebb93393ed891cbcebf2c481ecc #0.14.0_2025-08-21
    secrets: inherit
