name: publish autodoc

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      version:
        description: version to be published
        required: false
        type: string

jobs:
  publish:
    uses: sovity/core-edc-github/.github/workflows/publish-autodoc.yml@0.11.1_2025-03-10_3
    secrets: inherit
    with:
      version: ${{ github.event.inputs.version }}
