name: Release

on:
  workflow_dispatch:

jobs:

  Release:
    uses: sovity/core-edc-github/.github/workflows/release.yml@afc78987f721e601d228b50b55e098392397f006 #0.14.0_2025-08-21
    secrets: inherit
    with:
      publish-autodoc: true
