name: Release

on:
  workflow_dispatch:

jobs:

  Release:
    uses: sovity/core-edc-github/.github/workflows/release.yml@0.14.0_2025-08-21_3
    secrets: inherit
    with:
      publish-autodoc: true
