name: Release

on:
  workflow_dispatch:

jobs:

  Release:
    uses: sovity/core-edc-github/.github/workflows/release.yml@0.15.0_2025-12-05_2
    secrets: inherit
    with:
      publish-autodoc: true
