name: Scan Pull Request

on:
  pull_request:
    branches: [ main ]
    types: [opened, edited, synchronize, reopened, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger-workflow:
    uses: sovity/core-edc-github/.github/workflows/scan-pull-request.yml@255e962d85b9e0b972ced7cf9750e7333f172127 #pinned/0.17.0_2026-08-26 #main@2026-08-25
    secrets:
      envGH: ${{ secrets.GITHUB_TOKEN }}