name: Scan Pull Request

on:
  pull_request:
    branches: [ main ]
    types: [opened, edited, synchronize, reopened, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger-workflow:
    uses: sovity/core-edc-github/.github/workflows/scan-pull-request.yml@0.7.2_2025-01-22_1
    secrets:
      envGH: ${{ secrets.GITHUB_TOKEN }}