name: "Publish Snapshot Build"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Publish-Snapshot:
    # This workflow will abort if the required secrets don't exist
    uses: sovity/core-edc-github/.github/workflows/publish-snapshot.yml@afc78987f721e601d228b50b55e098392397f006 #0.14.0_2025-08-21
    secrets: inherit

  Publish-Dependencies:
    uses: sovity/core-edc-github/.github/workflows/publish-dependencies.yml@afc78987f721e601d228b50b55e098392397f006 #0.14.0_2025-08-21
    secrets: inherit
