name: "Publish Snapshot Build"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Publish-Snapshot:
    # This workflow will abort if the required secrets don't exist
    uses: sovity/core-edc-github/.github/workflows/publish-snapshot.yml@0.11.1_2025-03-10_2
    secrets: inherit

  Publish-Dependencies:
    uses: sovity/core-edc-github/.github/workflows/publish-dependencies.yml@0.11.1_2025-03-10_2
    secrets: inherit
